services:
  - type: web
    name: expense-analyzer
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
      - key: DATABASE_PATH
        value: data/transactions.db
      - key: LOG_LEVEL
        value: INFO
      - key: FUZZY_MATCH_THRESHOLD
        value: "86"
      - key: KEYWORD_CONFIDENCE
        value: "0.95"
      - key: FUZZY_CONFIDENCE_THRESHOLD
        value: "0.8"
      - key: LLM_CONFIDENCE
        value: "0.75"
      - key: MIN_WORD_LENGTH
        value: "3"
      - key: ENCODINGS_LIST
        value: '["utf-8", "cp1255", "iso-8859-8", "windows-1255"]'
      - key: DELIMITERS_LIST
        value: '[",", ";", "\t"]'
      - key: DEFAULT_MAPPING_PATH
        value: data/mapping.csv
      - key: MAX_FILE_SIZE_MB
        value: "10"
    healthCheckPath: /_stcore/health
    autoDeploy: true
