version: '3.8'

services:
  # Streamlit app (not exposed directly)
  expense-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-analyzer
    expose:
      - "8501"
    volumes:
      # Mount data directory to persist database
      - ./data:/app/data
      # Mount profiles for easy updates
      - ./data/profiles.yaml:/app/data/profiles.yaml
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Optional: OpenAI API Key for AI categorization
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - expense-net

  # Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: expense-analyzer-nginx
    ports:
      - "80:80"     # HTTP (redirects to HTTPS)
      - "443:443"   # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - expense-analyzer
    restart: unless-stopped
    networks:
      - expense-net

networks:
  expense-net:
    driver: bridge

volumes:
  data:
    driver: local
